fix: custom output checker の run スクリプトを修正 - Fail で動かなかったので条件追加 - 無駄な PE を削除

diff --git a/icpc2023-prelim/C/output_validators/run b/icpc2023-prelim/C/output_validators/run
--- a/icpc2023-prelim/C/output_validators/run
+++ b/icpc2023-prelim/C/output_validators/run
@@ -22,6 +22,8 @@ elif [ $EXITCODE -eq 1 ]; then
   exit 43  # WA
 elif [ $EXITCODE -eq 2 ]; then
   exit 43  # PE -> WA
+elif [ $EXITCODE -eq 3 ]; then
+  exit 43  # Fail -> WA
 else
   # その他のエラーはそのまま返す (Judge Error として扱う)
   exit $EXITCODE
diff --git a/icpc2025-prelim/F/output_validators/run b/icpc2025-prelim/F/output_validators/run
--- a/icpc2025-prelim/F/output_validators/run
+++ b/icpc2025-prelim/F/output_validators/run
@@ -20,8 +20,8 @@ if [ $EXITCODE -eq 0 ]; then
   exit 42  # AC
 elif [ $EXITCODE -eq 1 ]; then
   exit 43  # WA
-elif [ $EXITCODE -eq 2 ]; then
-  exit 43  # PE -> WA
+elif [ $EXITCODE -eq 3 ]; then
+  exit 43  # Fail -> WA
 else
   # その他のエラーはそのまま返す (Judge Error として扱う)
   exit $EXITCODE
